# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

posts = Post.create([
    { title: 'Eat your Vegetables (as garnish!)', image_url: 'gin&tonic.jpg', drink_name: 'the green drink', date: '2017, 4, 15', body: "I'll go over the colors one more time that we use: Titanium white, Thalo green, Prussian blue, Van Dyke brown, Alizarin crimson, Sap green, Cad yellow, and Permanent red. That's why I paint - because I can create the kind of world I want - and I can make this world as happy as I want it. Here's something that's fun. Nothing wrong with washing your brush. The very fact that you're aware of suffering is enough reason to be overjoyed that you're alive and can experience it. A big strong tree needs big strong roots.",
    ingredients: 'Gin, Lime, Cucumber, simple syrup', recipe: '2 ounces Gin, 1 ounce lime juice, 1/2 ounce simple syrup, and 1 cucumber spear', tags: 'garnish, gin, simple' },
    { title: 'More intruiging than you think..', image_url: 'Harvey_Wallbanger.jpg', drink_name: 'Harvey Wallbanger', date: '2017, 3, 12', body: "The only thing worse than yellow snow is green snow. You better get your coat out, this is going to be a cold painting. Let your heart be your guide. How do you make a round circle with a square knife? That's your challenge for the day. Follow the lay of the land. It's most important. You can't have light without dark. You can't know happiness unless you've known sorrow.  Maybe there's a little something happening right here. Let's have a little bit of fun today. There it is. You can't make a mistake. Anything that happens you can learn to use - and make something beautiful out of it.  We'll put some happy little leaves here and there. We artists are a different breed of people. We're a happy bunch. Isn't that fantastic? And just raise cain. Trees grow however makes them happy.",
    ingredients: 'Vodka, Galliano, Orange Juice', recipe: '1 ounce Vodka, 1/4 ounce Galliano, and 2 ounces Orange Juice', tags: 'simple, interesting, cheap' },
    { title: 'Classy and Bitter', image_url: 'negroni.jpg', drink_name: 'Negroni', date: '2017, 2, 20', body: "Just relax and let it flow. That easy. You can do anything your heart can imagine. Imagination is the key to painting.  You can get away with a lot. Even the worst thing we can do here is good. You need the dark in order to show the light. Now then, let's play. Every day I learn. Do an almighty painting with us.  I think there's an artist hidden in the bottom of every single one of us. Brown is such a nice color. Put light against light - you have nothing. Put dark against dark - you have nothing. It's the contrast of light and dark that each give the other one meaning. We'll do another happy little painting. You are only limited by your imagination.  You don't have to spend all your time thinking about what you're doing, you just let it happen. But we're not there yet, so we don't need to worry about it. Only think about one thing at a time. Don't get greedy. A fan brush is a fantastic piece of equipment. Use it. Make friends with it. Use absolutely no pressure. Just like an angel's wing.",
    ingredients: 'Gin, Sweet Vermouth, Campari', recipe: 'Equal Parts of each, typically one ounce.', tags: 'bitter, aperitif, simple' }
    ])
    
